language: java
rvm:
 - 11
 - java
install:
 - docker-compose build
 - docker login -u $login -p $pwddock
 - docker tag sampledb aguyot/sampledb
 - docker tag samplehttp aguyot/samplehttp
 - docker push aguyot/sampledb
 - docker push aguyot/samplehttp