language: java
rvm:
 - 11
 - java
install:
 - docker-compose build
 - docker login -u $login -p $pwddock
 - docker tag sample-application-students_sampledb aguyot/sampledb
 - docker tag sample-application-studentssamplehttp aguyot/samplehttp
 - docker push aguyot/sampledb
 - docker push aguyot/samplehttp