language: java

install:
 - mvn clean verify
 - docker-compose build
 - docker login -u $login -p $pwddock
 - docker tag sample-application-students_sampledb aguyot/sampledb
 - docker tag sample-application-students_samplehttp aguyot/samplehttp
 - docker push aguyot/sampledb
 - docker push aguyot/samplehttp

addons:
  sonarcloud:
    organization: "aguyot"
    token:
      secure: "nd3uH/r0y9m6rJ3d2NCPOXwjrkrbxEXVSa2JHvWTO4nUlIDMSq2qIq6tOVdBUeVzK3fJTlECZbK/joLqErJwFJP1MMY6WfGAIz5U6OY6Jj+pg3is9lJ6RN47cVw4VHS/dM1FpPyYtq9IaNtMYVW+gMe/qJlt1n2XENyYo6x19y26pgpTEZwtzmLdMRXXqXMw91h97wyPTBjVuj4fAKjEPQQZqoGvodVAsYfcga5GaCB+EjIOiqnWWJkqGVWWaEADp3JqZQdlrHz2Gn0hYaQn8a6jnVSy1Yd0UWSq7lBo1A4IxbNuCayzTYGZo0lvAqqpaS0hCgjMy39Iva/1DTTKNn7CC4pKwHJ0mxU1S5JDqdX3RpITP0Hgt3XkfapORSY/eeuDbYOz6QXzs6Lg3mCFWj4y1oPmcQMEUUxd2HkZa5SQroMSEFqDvulkLwbuWiVSCiHXfVou+qgcDLgGxWlllyZX1lqSDC8xkPYu4VPl+R+QrXCzvWd7Q4/atAFVq9pYw9Xf+LlxRVDX3S8skYuQfo/4Maqb3XJtt3EONV/jk4WbqIQH8GMEJYPWQB084ZHsxACnyJ2JVlZsqQ7Kil3ZgW+P8X0Pmqn/zeSZMTE9mhteRWLOtl4vsjJTh4Gbk+X4MVcmkMwTIl/vsFVtpCxEAuAAUk4gcc83ZTIs/mHu6ME=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - install sonar:sonar -Dsonar.projectKey=AGUYOT_sample-application-student